brace_style = "AlwaysNextLine"
combine_control_expr = false
condense_wildcard_suffixes = true
control_brace_style = "AlwaysNextLine"
empty_item_single_line = true
enum_discrim_align_threshold = 20
fn_single_line = true
format_doc_comments = true
format_strings = true
imports_indent = "Visual"
imports_layout = "HorizontalVertical"
indent_style = "Visual"
match_block_trailing_comma = true
merge_imports = true
reorder_impl_items = true
struct_field_align_threshold = 20
trailing_comma = "Never"
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true
